steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - ${_IMAGE}
      - -f
      - Dockerfile.agents
      - .
images:
  - ${_IMAGE}
substitutions:
  _IMAGE: us-central1-docker.pkg.dev/hamula-cfc6c/miras/hamula-agents
options:
  logging: CLOUD_LOGGING_ONLY
